TARGETS          := nrf52832_xxaa
OUTPUT_DIRECTORY := _build
DEBUG_BUILD      ?= 0

$(OUTPUT_DIRECTORY)/nrf52832_xxaa.out: \
  LINKER_SCRIPT  := $(PROJECT_ROOT)/src/nodes/common/nrf52.ld

# Source files common to all targets
SRC_FILES += \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/mdk/gcc_startup_nrf52.S \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/util/app_error.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/util/app_error_handler_gcc.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/util/app_error_weak.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/scheduler/app_scheduler.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/timer/app_timer.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/util/app_util_platform.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/atomic_fifo/nrf_atfifo.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/atomic_flags/nrf_atflags.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/atomic/nrf_atomic.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/pwr_mgmt/nrf_pwr_mgmt.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/ringbuf/nrf_ringbuf.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/experimental_section_vars/nrf_section_iter.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/mdk/system_nrf52.c \
  $(PROJECT_ROOT)/nrfsdk/components/boards/boards.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/src/nrfx_clock.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/src/nrfx_gpiote.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/src/prs/nrfx_prs.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/common/ble_advdata.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/common/ble_conn_params.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/common/ble_conn_state.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/common/ble_srv_common.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/ble_advertising/ble_advertising.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/nrf_ble_gatt/nrf_ble_gatt.c \
  $(PROJECT_ROOT)/nrfsdk/components/ble/nrf_ble_qwr/nrf_ble_qwr.c \
  $(PROJECT_ROOT)/nrfsdk/components/softdevice/common/nrf_sdh.c \
  $(PROJECT_ROOT)/nrfsdk/components/softdevice/common/nrf_sdh_ble.c \
  $(PROJECT_ROOT)/nrfsdk/components/softdevice/common/nrf_sdh_soc.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/src/nrfx_uarte.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/src/nrfx_uart.c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/src/nrfx_spim.c \
  $(PROJECT_ROOT)/nrfsdk/integration/nrfx/legacy/nrf_drv_uart.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/memobj/nrf_memobj.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/balloc/nrf_balloc.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/scheduler/app_scheduler.c \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/queue/nrf_queue.c \
  $(PROJECT_ROOT)/deca_driver/deca_device.c \
  $(PROJECT_ROOT)/deca_driver/deca_params_init.c \
  $(PROJECT_ROOT)/src/nodes/common/bluetooth.cpp \
  $(PROJECT_ROOT)/src/nodes/common/dw1000.cpp \
  $(PROJECT_ROOT)/src/nodes/common/utilities.cpp \
  $(PROJECT_ROOT)/src/nodes/common/cli.cpp \
  $(PROJECT_ROOT)/src/nodes/common/core.cpp

# Include folders common to all targets
INC_FOLDERS += \
  $(PROJECT_ROOT)/gsl/include \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/bsp \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/hal \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/log \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/mutex \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/gpiote \
  $(PROJECT_ROOT)/nrfsdk/components/boards \
  $(PROJECT_ROOT)/nrfsdk/components/ble/ble_advertising \
  $(PROJECT_ROOT)/nrfsdk/components/ble/ble_services/ble_bas_c \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/drivers/include \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/pwr_mgmt \
  $(PROJECT_ROOT)/nrfsdk/components/toolchain/cmsis/include \
  $(PROJECT_ROOT)/nrfsdk/components/ble/common \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/experimental_section_vars \
  $(PROJECT_ROOT)/nrfsdk/components/softdevice/s132/headers \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/delay \
  $(PROJECT_ROOT)/nrfsdk/components/softdevice/common \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/atomic \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/util \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/timer \
  $(PROJECT_ROOT)/nrfsdk/integration/nrfx \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx/mdk \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/strerror \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/ringbuf \
  $(PROJECT_ROOT)/nrfsdk/components/ble/nrf_ble_gatt \
  $(PROJECT_ROOT)/nrfsdk/components/ble/nrf_ble_qwr \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/button \
  $(PROJECT_ROOT)/nrfsdk/modules/nrfx \
  $(PROJECT_ROOT)/nrfsdk/integration/nrfx/legacy \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/atomic_flags \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/log/src \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/memobj \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/balloc \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/scheduler \
  $(PROJECT_ROOT)/nrfsdk/external/fprintf \
  $(PROJECT_ROOT)/nrfsdk/components/libraries/queue \
  $(PROJECT_ROOT)/deca_driver \
  $(PROJECT_ROOT)/src/nodes/common
  
# Libraries common to all targets
LIB_FILES += \

# C flags common to all targets
CFLAGS += $(OPT)
CFLAGS += -DGIT_COMMIT=\"$(shell git show -s --format=%h)\"
CFLAGS += -DCUSTOM_BOARD_INC=dwm1001_board
CFLAGS += -DCONFIG_GPIO_AS_PINRESET
CFLAGS += -DFLOAT_ABI_HARD
CFLAGS += -DNRF52
CFLAGS += -DNRF52832_XXAA
CFLAGS += -DNRF52_PAN_74
CFLAGS += -DNRF_SD_BLE_API_VERSION=6
CFLAGS += -DS132
CFLAGS += -DSOFTDEVICE_PRESENT
CFLAGS += -DSWI_DISABLE0
CFLAGS += -mcpu=cortex-m4
CFLAGS += -mthumb -mabi=aapcs
CFLAGS += -Wall -Werror
CFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
# keep every function in a separate section, this allows linker to discard unused ones
CFLAGS += -ffunction-sections -fdata-sections -fno-strict-aliasing
CFLAGS += -fno-builtin -fshort-enums
CFLAGS += -flto
ifeq ($(DEBUG_BUILD), 1)
    CFLAGS += -g3
else
    CFLAGS += -O3
endif

# C++ flags common to all targets
CXXFLAGS += $(CFLAGS)
CXXFLAGS += -std=c++17
CXXFLAGS += -fno-rtti -fno-exceptions

# Assembler flags common to all targets
ASMFLAGS += -mcpu=cortex-m4
ASMFLAGS += -mthumb -mabi=aapcs
ASMFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
ASMFLAGS += -DCUSTOM_BOARD_INC=dwm1001_board
ASMFLAGS += -DCONFIG_GPIO_AS_PINRESET
ASMFLAGS += -DFLOAT_ABI_HARD
ASMFLAGS += -DNRF52
ASMFLAGS += -DNRF52832_XXAA
ASMFLAGS += -DNRF52_PAN_74
ASMFLAGS += -DNRF_SD_BLE_API_VERSION=6
ASMFLAGS += -DS132
ASMFLAGS += -DSOFTDEVICE_PRESENT
ASMFLAGS += -DSWI_DISABLE0
ifeq ($(DEBUG_BUILD), 1)
    ASMFLAGS += -g3
endif

# Linker flags
LDFLAGS += $(OPT)
LDFLAGS += -mthumb -mabi=aapcs -L$(PROJECT_ROOT)/nrfsdk/modules/nrfx/mdk -T$(LINKER_SCRIPT)
LDFLAGS += -mcpu=cortex-m4
LDFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16
# let linker dump unused sections
LDFLAGS += -Wl,--gc-sections
# use newlib in nano version
LDFLAGS += --specs=nano.specs

ifeq ($(DEBUG_BUILD), 1)
    CFLAGS += -DEBUG_BUILD
    CXXFLAGS += -DEBUG_BUILD
endif

nrf52832_xxaa: CFLAGS += -D__HEAP_SIZE=8192
nrf52832_xxaa: CFLAGS += -D__STACK_SIZE=8192
nrf52832_xxaa: ASMFLAGS += -D__HEAP_SIZE=8192
nrf52832_xxaa: ASMFLAGS += -D__STACK_SIZE=8192

# Add standard libraries at the very end of the linker input, after all objects
# that may need symbols provided by these libraries.
LIB_FILES += -lc -lnosys -lm


.PHONY: default help

# Default target - first one defined
default: nrf52832_xxaa

# Print all targets that can be built
help:
	@echo following targets are available:
	@echo		nrf52832_xxaa
	@echo		flash_softdevice
	@echo		sdk_config - starting external tool for editing sdk_config.h
	@echo		flash      - flashing binary

TEMPLATE_PATH := $(PROJECT_ROOT)/nrfsdk/components/toolchain/gcc

include $(TEMPLATE_PATH)/Makefile.common

$(foreach target, $(TARGETS), $(call define_target, $(target)))

.PHONY: flash flash_softdevice erase
BOARD_ID ?= $(shell nrfjprog -i | head -n 1)

# Flash the program
flash: default
	@echo Flashing: $(OUTPUT_DIRECTORY)/nrf52832_xxaa.hex
	nrfjprog -s $(BOARD_ID) -f nrf52 --program $(OUTPUT_DIRECTORY)/nrf52832_xxaa.hex --sectorerase
	nrfjprog -s $(BOARD_ID) -f nrf52 --reset

# Flash softdevice
flash_softdevice:
	@echo Flashing: s132_nrf52_6.1.0_softdevice.hex
	nrfjprog -s $(BOARD_ID) -f nrf52 --program $(PROJECT_ROOT)/nrfsdk/components/softdevice/s132/hex/s132_nrf52_6.1.0_softdevice.hex --sectorerase
	nrfjprog -s $(BOARD_ID) -f nrf52 --reset

erase:
	nrfjprog -s $(BOARD_ID) -f nrf52 --eraseall

SDK_CONFIG_FILE := ../config/sdk_config.h
CMSIS_CONFIG_TOOL := $(PROJECT_ROOT)/nrfsdk/external_tools/cmsisconfig/CMSIS_Configuration_Wizard.jar
sdk_config:
	java -jar $(CMSIS_CONFIG_TOOL) $(SDK_CONFIG_FILE)
