PROJECT_NAME := ss-twr-anchor
PROJECT_ROOT := ../../../..

# Source files common to all targets
SRC_FILES := \
  main.cpp

# Include folders common to all targets
#INC_FOLDERS += \

include $(PROJECT_ROOT)/src/nodes/examples/common/Makefile.common
