PROJECT_NAME := cli
PROJECT_ROOT := ../../../..

# Source files common to all targets
SRC_FILES := \
  main.cpp

# Include folders common to all targets
#INC_FOLDERS += \

include $(PROJECT_ROOT)/src/nodes/common/Makefile.common
